[[OpenMPI]]
arch = "aarch64"
git-tree-sha1 = "fef4078f3ea1aadd7d5a4c8c775a3a9ecfebaebf"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[OpenMPI.download]]
    sha256 = "c517c4f7ab633d9fe2f3882e0d860d563e2dcdb3f73af861372dece619c4b7b0"
    url = "https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/releases/download/OpenMPI-v5.0.8+0/OpenMPI.v5.0.8.aarch64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[OpenMPI]]
arch = "aarch64"
git-tree-sha1 = "5aefba22625c37debfa3cb714de7a78b49bc8877"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "openmpi"
os = "linux"

    [[OpenMPI.download]]
    sha256 = "47bf1fda04d54a3df60f55e55872c7ce19fb8a3b3045995f0bfe91d7496b4b44"
    url = "https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/releases/download/OpenMPI-v5.0.8+0/OpenMPI.v5.0.8.aarch64-linux-gnu-libgfortran3-mpi+openmpi.tar.gz"
[[OpenMPI]]
arch = "aarch64"
git-tree-sha1 = "17d5d1baadadb851938051806389ccd6903a0171"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "openmpi"
os = "linux"

    [[OpenMPI.download]]
    sha256 = "d98c6773881bbb882804f10e541ba070af289d8803dadadfaf0fa1ccb7586820"
    url = "https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/releases/download/OpenMPI-v5.0.8+0/OpenMPI.v5.0.8.aarch64-linux-gnu-libgfortran4-mpi+openmpi.tar.gz"
[[OpenMPI]]
arch = "aarch64"
git-tree-sha1 = "4bd6895aac99addb89d00fd6b3abb16ae4472454"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[OpenMPI.download]]
    sha256 = "f5ceb706670a17074ef88a536f641a3407328f0bdbbda17bf95219d86bdfa399"
    url = "https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/releases/download/OpenMPI-v5.0.8+0/OpenMPI.v5.0.8.aarch64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[OpenMPI]]
arch = "aarch64"
git-tree-sha1 = "d905de4a7a4340a448ae68970c331a6cff387bcd"
lazy = true
libc = "musl"
libgfortran_version = "3.0.0"
mpi = "openmpi"
os = "linux"

    [[OpenMPI.download]]
    sha256 = "0f6ccacf43c35370beb96cc9954e7e794e21b5880b1290bda88c36f4c476005c"
    url = "https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/releases/download/OpenMPI-v5.0.8+0/OpenMPI.v5.0.8.aarch64-linux-musl-libgfortran3-mpi+openmpi.tar.gz"
[[OpenMPI]]
arch = "aarch64"
git-tree-sha1 = "600a18898d297c342af57648cc6ee5fb5190e959"
lazy = true
libc = "musl"
libgfortran_version = "4.0.0"
mpi = "openmpi"
os = "linux"

    [[OpenMPI.download]]
    sha256 = "fa785c50391797794a8a3a86f7851921c5d4759e226e8a0d16e6fd3e245affde"
    url = "https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/releases/download/OpenMPI-v5.0.8+0/OpenMPI.v5.0.8.aarch64-linux-musl-libgfortran4-mpi+openmpi.tar.gz"
[[OpenMPI]]
arch = "aarch64"
git-tree-sha1 = "369ae2e6b8a308559792563187fad2b779fc0767"
lazy = true
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[OpenMPI.download]]
    sha256 = "6aa1e160e5addb8a6b28f7dbe1f99f580a6e097bee4e83b12aff8d98f30d1a56"
    url = "https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/releases/download/OpenMPI-v5.0.8+0/OpenMPI.v5.0.8.aarch64-linux-musl-libgfortran5-mpi+openmpi.tar.gz"
[[OpenMPI]]
arch = "powerpc64le"
git-tree-sha1 = "aa0ef36ed03c4178884e4aa9debf6be9edec9c42"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "openmpi"
os = "linux"

    [[OpenMPI.download]]
    sha256 = "019cfb8b9b71c5715b52588c0c7160215e76cab1a31d695c240c4368e088b405"
    url = "https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/releases/download/OpenMPI-v5.0.8+0/OpenMPI.v5.0.8.powerpc64le-linux-gnu-libgfortran3-mpi+openmpi.tar.gz"
[[OpenMPI]]
arch = "powerpc64le"
git-tree-sha1 = "28ee1c967799803af1d386c03a5a052efeebfb8e"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "openmpi"
os = "linux"

    [[OpenMPI.download]]
    sha256 = "095a4aab98c072850068bc1b070b54779fdd2ec0cecc2332191ff2b00a952e4f"
    url = "https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/releases/download/OpenMPI-v5.0.8+0/OpenMPI.v5.0.8.powerpc64le-linux-gnu-libgfortran4-mpi+openmpi.tar.gz"
[[OpenMPI]]
arch = "powerpc64le"
git-tree-sha1 = "59403030a70af1dfb66ea20033366d9da6063ade"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[OpenMPI.download]]
    sha256 = "2cfd4c53cec8b3dede7cffbbb97dffd5ba882ce7b911840f077cd760fed4c832"
    url = "https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/releases/download/OpenMPI-v5.0.8+0/OpenMPI.v5.0.8.powerpc64le-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[OpenMPI]]
arch = "riscv64"
git-tree-sha1 = "0950fd221816909d56734389c17e3b59ec8f55f3"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[OpenMPI.download]]
    sha256 = "8d63fb0bf899735eb9a63a93b631f2d56e14fb023762c29efe9c51d07c89669f"
    url = "https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/releases/download/OpenMPI-v5.0.8+0/OpenMPI.v5.0.8.riscv64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[OpenMPI]]
arch = "x86_64"
git-tree-sha1 = "0b175f27dd3b1070a1f211811c3b9ea5e7c5f803"
lazy = true
libgfortran_version = "3.0.0"
mpi = "openmpi"
os = "macos"

    [[OpenMPI.download]]
    sha256 = "a417fa166f390354af67ec5fffbdf582d8a68a1d152dcb9467185a8b1600393f"
    url = "https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/releases/download/OpenMPI-v5.0.8+0/OpenMPI.v5.0.8.x86_64-apple-darwin-libgfortran3-mpi+openmpi.tar.gz"
[[OpenMPI]]
arch = "x86_64"
git-tree-sha1 = "89de191f8cd1146521f4afca650b69a139a29d89"
lazy = true
libgfortran_version = "4.0.0"
mpi = "openmpi"
os = "macos"

    [[OpenMPI.download]]
    sha256 = "6235fd9e668854b907ff944f2853fcada15abbd95a22992f89e329a044b9a5e3"
    url = "https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/releases/download/OpenMPI-v5.0.8+0/OpenMPI.v5.0.8.x86_64-apple-darwin-libgfortran4-mpi+openmpi.tar.gz"
[[OpenMPI]]
arch = "x86_64"
git-tree-sha1 = "82d1833232c19bf08bbdad0e8351345bd3552745"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[OpenMPI.download]]
    sha256 = "e745306517723abb631212b078d9d00ec5649b4cbf6099412d707bbdaf96e331"
    url = "https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/releases/download/OpenMPI-v5.0.8+0/OpenMPI.v5.0.8.x86_64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[OpenMPI]]
arch = "x86_64"
git-tree-sha1 = "4bbadb88a80b623a4672e73a0b9dfbaf8709748e"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "openmpi"
os = "linux"

    [[OpenMPI.download]]
    sha256 = "3b1dcaa033365cc862b3e62deba79729e6fbed447d23704ba9f231323ce4a33c"
    url = "https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/releases/download/OpenMPI-v5.0.8+0/OpenMPI.v5.0.8.x86_64-linux-gnu-libgfortran3-mpi+openmpi.tar.gz"
[[OpenMPI]]
arch = "x86_64"
git-tree-sha1 = "059ea1c2323c78b142d7484917eb6cf07b82812f"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "openmpi"
os = "linux"

    [[OpenMPI.download]]
    sha256 = "566cd78d1204be8415f0aa847673642e1d4b740e122efad4be3b680eeac84720"
    url = "https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/releases/download/OpenMPI-v5.0.8+0/OpenMPI.v5.0.8.x86_64-linux-gnu-libgfortran4-mpi+openmpi.tar.gz"
[[OpenMPI]]
arch = "x86_64"
git-tree-sha1 = "695bf0397a849eab58cd21bf28f8c4279cfa42ad"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[OpenMPI.download]]
    sha256 = "b918a5140afdc3e5cd092a774206abe3d6fd56b4913ec3a1edd308c43acf9849"
    url = "https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/releases/download/OpenMPI-v5.0.8+0/OpenMPI.v5.0.8.x86_64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[OpenMPI]]
arch = "x86_64"
git-tree-sha1 = "d3d9af9d9167606b91182246348accd8b11936dc"
lazy = true
libc = "musl"
libgfortran_version = "3.0.0"
mpi = "openmpi"
os = "linux"

    [[OpenMPI.download]]
    sha256 = "da08eec61687d9ea8a64ec3614711522adeb83b9c862df7b0fe2d0fe76f646a5"
    url = "https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/releases/download/OpenMPI-v5.0.8+0/OpenMPI.v5.0.8.x86_64-linux-musl-libgfortran3-mpi+openmpi.tar.gz"
[[OpenMPI]]
arch = "x86_64"
git-tree-sha1 = "e1d86689657b9d26666d857802f415aa5b777f2d"
lazy = true
libc = "musl"
libgfortran_version = "4.0.0"
mpi = "openmpi"
os = "linux"

    [[OpenMPI.download]]
    sha256 = "29903b89897b96a811eb4ba9e528cc4a2111b69c1c8d02ff0714b44422f90661"
    url = "https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/releases/download/OpenMPI-v5.0.8+0/OpenMPI.v5.0.8.x86_64-linux-musl-libgfortran4-mpi+openmpi.tar.gz"
[[OpenMPI]]
arch = "x86_64"
git-tree-sha1 = "f6a7f27b3963d97004f4c57b4be54298d18054df"
lazy = true
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[OpenMPI.download]]
    sha256 = "34f7fbb087dde7855c447a228e3639e920868d0837af73b7208ad7fb969c2360"
    url = "https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/releases/download/OpenMPI-v5.0.8+0/OpenMPI.v5.0.8.x86_64-linux-musl-libgfortran5-mpi+openmpi.tar.gz"
